### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by ccoz** [tignioj/RightClickFileBrowser#1]
系统找不到指定的文件。
''2'' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'C:\Users\codeyang\Desktop\RightClickFileBrowser-main\'' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'rowser.exe" (' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
请按任意键继续. . .

**Comment by tignioj** [comment]
感谢反馈！排查是脚本中含有**中文注释**导致的，目前已经删掉所有中文注释，你重新下载目前[发布的最新版](https://github.com/tignioj/RightClickFileBrowser/releases/download/V1.0/V1.0-RightClickFileBrowser.7z)，再试试看。

**Comment by ccoz** [comment]
现在已经可以了
